// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using students.Data;

#nullable disable

namespace students.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524072654_InitSQLite")]
    partial class InitSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("students.Models.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("students.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloudFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RelatedCourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UploaderStudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("students.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("management")
                        .HasColumnType("INTEGER");

                    b.Property<string>("studentEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("studentPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("students.Models.StudentInCourse", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInPerson")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("StudentId", "CourseId");

                    b.ToTable("StudentInCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
